### ISSUE TITLE
Set HTTP security headers 

### ISSUE THREAD

**Issue by thec00n** [omisego/web-wallet#33]
### Description 
Let's consider HTTP security headers (check https://owasp.org/www-project-secure-headers/ to learn more about what that is) where it makes sense and does not impact functionality. For simplicity we could consider using https://www.npmjs.com/package/helmet but up for discussion.

**Comment by nicholasmueller** [comment]
@thec00n web wallet is purely client side so its not serving any responses, only making requests to our services. closing unless im misunderstanding something..
