### ISSUE TITLE
WebWallet Conformance: Trust

### ISSUE THREAD

**Issue by okalouti** [omisego/web-wallet#53]

**Comment by nicholasmueller** [comment]
cors errors, fantastic 

![trust cors](https://user-images.githubusercontent.com/29919550/82034163-06353f80-96c8-11ea-8719-093fe7e63b63.PNG)
![trust signing](https://user-images.githubusercontent.com/29919550/82034179-0a615d00-96c8-11ea-88cf-440b1268b196.PNG)
