### ISSUE TITLE
WebWallet Mobile Responsiveness

### ISSUE THREAD

**Issue by okalouti** [omisego/web-wallet#57]
Ensure that the web wallet looks good on Android & iOS

**Comment by okalouti** [comment]
Pending designs from @noninoei

**Comment by nicholasmueller** [comment]
new designs:
https://gallery.io/projects/MCHbtQVoQ2HCZe9U2R-hJAvE/files/MCG-r3vwFhlMMY64zQ0MjPSa
https://gallery.io/projects/MCHbtQVoQ2HCZe9U2R-hJAvE/files/MCETG-LQ_bvwT321hJkk-Qxx
